export const PopularOnTV = {
  FETCH_POPULAR_ON_TV_START: "FETCH_POPULAR_ON_TV_START",
  FETCH_POPULAR_ON_TV_SUCCESS: "FETCH_POPULAR_ON_TV_SUCCESS",
  FETCH_POPULAR_ON_TV_FAILURE: "FETCH_POPULAR_ON_TV_FAILURE",
};

export const LatestOnTv = {
  FETCH_LATEST_ON_TV_START: "FETCH_LATEST_ON_TV_START",
  FETCH_LATEST_ON_TV_SUCCESS: "FETCH_LATEST_ON_TV_SUCCESS",
  FETCH_LATEST_ON_TV_FAILURE: "FETCH_LATEST_ON_TV_FAILURE",
};

export const TopRatedOnTv = {
  FETCH_TOP_RATED_ON_TV_START: "FETCH_TOP_RATED_ON_TV_START",
  FETCH_TOP_RATED_ON_TV_SUCCESS: "FETCH_TOP_RATED_ON_TV_SUCCESS",
  FETCH_TOP_RATED_ON_TV_FAILURE: "FETCH_TOP_RATED_ON_TV_FAILURE",
};

export const OnAirOnTv = {
  FETCH_ON_AIR_ON_TV_START: "FETCH_ON_AIR_ON_TV_START",
  FETCH_ON_AIR_ON_TV_SUCCESS: "FETCH_ON_AIR_ON_TV_SUCCESS",
  FETCH_ON_AIR_ON_TV_FAILURE: "FETCH_ON_AIR_ON_TV_FAILURE",
};
