export const PopularOnTV = {
  FETCH_POPULAR_ON_TV_START: "FETCH_POPULAR_ON_TV_START",
  FETCH_POPULAR_ON_TV_SUCCESS: "FETCH_POPULAR_ON_TV_SUCCESS",
  FETCH_POPULAR_ON_TV_FAILURE: "FETCH_POPULAR_ON_TV_FAILURE",
};
