export const TRENDING_MOVIES = {
  FETCH_TRENDING_MOVIE_START: "FETCH_TRENDING_MOVIE_START",
  FETCH_TRENDING_MOVIE_SUCCESS: "FETCH_TRENDING_MOVIE_SUCCESS",
  FETCH_TRENDING_MOVIE_FAILURE: "FETCH_TRENDING_MOVIE_FAILURE",
};
