const RECOMMEND = {
  FETCH_RECOMMEND_START: 'FETCH_RECOMMEND_START',
  FETCH_RECOMMEND_SUCCESS: 'FETCH_RECOMMEND_SUCCESS',
  FETCH_RECOMMEND_FAILURE: 'FETCH_RECOMMEND_FAILURE',
};

export default RECOMMEND;
