export const POPULAR_MOVIES = {
  FETCH_POPULAR_MOVIE_START: "FETCH_POPULAR_MOVIE_START",
  FETCH_POPULAR_MOVIE_SUCCESS: "FETCH_POPULAR_MOVIE_SUCCESS",
  FETCH_POPULAR_MOVIE_FAILURE: "FETCH_POPULAR_MOVIE_FAILURE",
};
