export const UPCOMING_MOVIES = {
  FETCH_UPCOMING_START: "FETCH_UPCOMING_START",
  FETCH_UPCOMING_SUCCESS: "FETCH_UPCOMING_SUCCESS",
  FETCH_UPCOMING_FAILURE: "FETCH_UPCOMING_FAILURE",
};

export const TRENDING_MOVIES = {
  FETCH_TRENDING_MOVIE_START: "FETCH_TRENDING_MOVIE_START",
  FETCH_TRENDING_MOVIE_SUCCESS: "FETCH_TRENDING_MOVIE_SUCCESS",
  FETCH_TRENDING_MOVIE_FAILURE: "FETCH_TRENDING_MOVIE_FAILURE",
};

export const TOPRATED_MOVIES = {
  FETCH_TOPRATED_MOVIE_START: "FETCH_TOPRATED_MOVIE_START",
  FETCH_TOPRATED_MOVIE_SUCCESS: "FETCH_TOPRATED_MOVIE_SUCCESS",
  FETCH_TOPRATED_MOVIE_FAILURE: "FETCH_TOPRATED_MOVIE_FAILURE",
};
export const POPULAR_MOVIES = {
  FETCH_POPULAR_MOVIE_START: "FETCH_POPULAR_MOVIE_START",
  FETCH_POPULAR_MOVIE_SUCCESS: "FETCH_POPULAR_MOVIE_SUCCESS",
  FETCH_POPULAR_MOVIE_FAILURE: "FETCH_POPULAR_MOVIE_FAILURE",
};

export const DISCOVER_MOVIES = {
  FETCH_DISCOVER_MOVIE_START: "FETCH_DISCOVER_MOVIE_START",
  FETCH_DISCOVER_MOVIE_SUCCESS: "FETCH_DISCOVER_MOVIE_SUCCESS",
  FETCH_DISCOVER_MOVIE_FAILURE: "FETCH_DISCOVER_MOVIE_FAILURE",
};
export const NOW_PLAYING_MOVIES = {
  FETCH_NOW_PLAYING_MOVIE_START: "FETCH_NOW_PLAYING_MOVIE_START",
  FETCH_NOW_PLAYING_MOVIE_SUCCESS: "FETCH_NOW_PLAYING_MOVIE_SUCCESS",
  FETCH_NOW_PLAYING_MOVIE_FAILURE: "FETCH_NOW_PLAYING_MOVIE_FAILURE",
};
