export const POPULAR = {
  FETCH_POPULAR_START: 'FETCH_POPULAR_START',
  FETCH_POPULAR_SUCCESS: 'FETCH_POPULAR_SUCCESS',
  FETCH_POPULAR_FAILURE: 'FETCH_POPULAR_FAILURE',
};

export const TOPRATED = {
  FETCH_TOPRATED_START: 'FETCH_TOPRATED_START',
  FETCH_TOPRATED_SUCCESS: 'FETCH_TOPRATED_SUCCESS',
  FETCH_TOPRATED_FAILURE: 'FETCH_TOPRATED_FAILURE',
};

export const TRENDING = {
  FETCH_TRENDING_START: 'FETCH_TRENDING_START',
  FETCH_TRENDING_SUCCESS: 'FETCH_TRENDING_SUCCESS',
  FETCH_TRENDING_FAILURE: 'FETCH_TRENDING_FAILURE',
};

export const UPCOMING = {
  FETCH_UPCOMING_START: 'FETCH_UPCOMING_START',
  FETCH_UPCOMING_SUCCESS: 'FETCH_UPCOMING_SUCCESS',
  FETCH_UPCOMING_FAILURE: 'FETCH_UPCOMING_FAILURE',
};

export const MOVIE = {
  FETCH_MOVIE_START: 'FETCH_MOVIE_START',
  FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
  FETCH_MOVIE_FAILURE: 'FETCH_MOVIE_FAILURE',
};
