export const TOPRATED_MOVIES = {
  FETCH_TOPRATED_MOVIE_START: "FETCH_TOPRATED_MOVIE_START",
  FETCH_TOPRATED_MOVIE_SUCCESS: "FETCH_TOPRATED_MOVIE_SUCCESS",
  FETCH_TOPRATED_MOVIE_FAILURE: "FETCH_TOPRATED_MOVIE_FAILURE",
};
