export const DISCOVER_MOVIES = {
  FETCH_DISCOVER_MOVIE_START: "FETCH_DISCOVER_MOVIE_START",
  FETCH_DISCOVER_MOVIE_SUCCESS: "FETCH_DISCOVER_MOVIE_SUCCESS",
  FETCH_DISCOVER_MOVIE_FAILURE: "FETCH_DISCOVER_MOVIE_FAILURE",
};
